project:
  type: website
  output-dir: docs

website:
  title: "K.V. Hernandez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - fiction.qmd
      - href: posts.qmd
        text: Research

format:
  html:
    theme:
      light: journal 
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual
